config/routes.rb
Rails.application.routes.draw do
  resources :roles

  resources :users do
    member do
      get :edit_password
      put :update_password
      get :edit_verification
      put :update_verification
    end
  end

  resources :password_reset_requests

  match "signin", :to => "accounts#signin", :as => "login"
  match "signout", :to => "accounts#signout", :as => "logout"
  match "permission_denied", :to => "accounts#permission_denied"
end

app/models/user.rb
require 'digest/sha2'

class User < ActiveRecord::Base
  has_many :password_reset_requests, :order => 'created_at DESC'
  has_and_belongs_to_many :roles
  before_validation(:clobber_existing_unverified_user, :on => :create)

  to_protect = :url_safe_name, :password_hash, :password_salt, :verified
  to_protect << :username unless Azimux::AxUser.allow_username_edits
  attr_protected to_protect

  validates_uniqueness_of :username
  validates_uniqueness_of :url_safe_name
  validates_presence_of :email, :username, :url_safe_name
  validates_format_of :email, :with => Azimux::EMAIL_REGEX,
    :if => Proc.new {|u| !u.email.blank?}
  validates_format_of :url_safe_name, :with => /[[:lower:]\d_]+/

  def clobber_existing_unverified_user
    other_user = User.find_by_username_and_verified(username, false)

    other_user.destroy if other_user
  end

  # Username can be the user's email.
  # Returns a user if authentication was succesful, nil otherwise
  def self.authenticate(username, password)
    user = User.find(:first, :conditions => ['username = ?', username])
    user ||= User.find(:first, :conditions => ['email = ?', username])

    if user
      if Digest::SHA256.hexdigest(password + user.password_salt) == user.password_hash
        user
      end
    end
  end

  def password=(pass)
    hs = User.make_password_hash_and_salt(pass)
    self.password_salt, self.password_hash = hs.salt, hs.hash
  end

  def self.make_password_hash_and_salt(pass)
    hs = Struct.new(:salt,:hash).new
    hs.salt = [Array.new(6){rand(256).chr}.join].pack("m").chomp
    hs.hash = Digest::SHA256.hexdigest(pass+hs.salt)
    hs
  end

  def email=(email)
    super(email ? email.strip : email)
  end

  def in_role?(role)
    roles.detect do |r|
      r.in_role?(role)
    end
  end

  def self.url_safe_name username
    username.downcase.gsub(/[\W]/, '_')
  end

  def username= uname
    self.url_safe_name = User.url_safe_name(uname)
    write_attribute(:username, uname)
  end

  def password_reset_request
    password_reset_requests.first
  end

  #dummy methods for providing blank password fields
  def password1
  end
  def password2
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  require_login :only => [:edit, :update, :destroy]
  before_filter :only => [:edit, :update, :destroy] do |c|
    c.instance_eval do
      unless params[:id] && session[:user] && params[:id].to_i == session[:user].to_i &&
          session[:user].to_i > 0
        redirect_to_permission_denied
      end
    end
  end

  if Azimux::AxUser.ssl_enabled?
    Azimux::AxUser.install_ssl_rules
  end

  def new
    @user = User.new
    Azimux::AxUser.additional_registration_models.each do |model|
      instance_eval(&model.new_proc)
    end
  end

  def create
    password1 = params[:user].delete :password1
    password2 = params[:user].delete :password2

    @user = User.new(params[:user])

    #Make sure the passwords match
    if password1 != password2
      @user.errors.add(:password1, "The passwords you entered did not match.")
      @user.errors.add(:password2, "The passwords you entered did not match.")
      render :action => "new"
      return
    end

    if password1.blank?
      @user.errors.add(:password1, "You must provide a password.")
      @user.errors.add(:password2, "You must verify your password.")
      render :action => "new"
      return
    end

    @user.verified = false
    @user.password = password1

    @user.verify_code = Azimux.generate_verify_code

    models = Azimux::AxUser.additional_registration_models
    objects = models.map{|m|instance_eval(&m.create_init_proc)}

    User.transaction do
      success = @user.save && models.map do |model|
                                instance_eval(&model.create_proc)
                              end.all?

      if success
        VerifyMailer.verify(@user).deliver
      else
        render :action => "new"
        raise ActiveRecord::Rollback
      end
    end
  end

  def edit
    @user = User.find(params[:id])

    Azimux::AxUser.additional_registration_models.each do |model|
      instance_eval(&model.edit_proc)
    end
  end

  def update
    User.transaction do
      @user = User.find(params[:id])

      unless Azimux::AxUser.allow_username_edits
        params[:user].delete(:username)
      end

      if @user.id != user.id
        raise "user #{user.id} trying to change password of user #{@user.id}"
      end

      models = Azimux::AxUser.additional_registration_models
      objects = models.map{|m|instance_eval(&m.update_init_proc)}

      User.transaction do
        success = @user.update_attributes(@user.attributes.merge(params[:user]))

        if success
          success = models.map do |model|
                      instance_eval(&model.update_proc)
                    end.all?
        end

        if success
          flash[:notice] = "Successfully updated your account settings"
          redirect_to edit_user_url(@user)
        else
          render :action => "edit"
          raise ActiveRecord::Rollback
        end
      end
    end
  end

  def edit_password
    @user = User.find(params[:id])
  end

  def update_password
    password1 = params[:password1]
    password2 = params[:password2]
    password = params[:password]
    @user = User.find(params[:id])

    if params[:code]
      code = params[:code]

      if !(code.length == Azimux::VERIFY_CODE_LENGTH &&
            @user.password_reset_request &&
            @user.password_reset_request.code == code)
        flash[:notice] = "The reset password code that you used from your email is not valid, try again."
        redirect_to new_password_reset_request_url
        return
      end
    else
      unless User.authenticate(@user.username, password)
        @user.errors.add(:base, "The password you entered doesn't match your current password")
        render :action => "edit_password"
        return
      end
    end

    if password1 != password2
      @user.errors.add(:base, "The passwords you entered did not match.")
      render :action => "edit_password"
      return
    end

    if :password1.blank?
      @user.errors.add(:base, "You must provide a password.")
      render :action => "edit_password"
      return
    end


    User.transaction do
      @user.password = password1
      respond_to do |format|
        if @user.save && @user.password_reset_requests.destroy_all
          flash[:notice] = 'Password was successfully changed.  You may now login'
          format.html { redirect_to login_url }
        else
          raise "Something unexpectedly prevented this user #{@user.username} #{@user.id} from updating their password."
        end
      end
    end
  end

  def edit_verification
    @user = User.find(params[:id])
  end

  def update_verification
    User.transaction do
      @user = User.find(params[:id])

      code = params[:code]

      if code.length == Azimux::VERIFY_CODE_LENGTH && @user.verify_code == code
        @user.verified = true
        @user.verify_code = nil

        if @user.save!
          if Role.find_by_name('admin').users.size == 0
            @user.roles << Role.find_by_name('admin')
            @user.save!
          end

          flash[:notice] = 'Your account is activated.  You may now sign in.'
          redirect_to login_url
        end
      end
    end
  end
end

app/views/users/_new_or_edit.html.erb
<% if mode == "new" %>
  <h1>Register</h1>
<% elsif mode == "edit" %>
  <h1>Update your account settings</h1>
<% else
  raise "Invalid mode: #{mode}"
end
%>
<%
url_for_opts = {:protocol => "https"} if Azimux::AxUser.ssl_enabled?
url_for_opts ||= {}
%>
<%#= error_messages_for :user, :object_name => "",
:header_message => "Some errors occured while trying to register:" %>

<% if mode == "edit" %>
  <%#= link_to "Change password", edit_password_user_url(user) -%>
  <%= form_tag edit_password_user_url(user), :method => "get" do %>
    <%= submit_tag "Change Password " -%>
  <% end %>
  <hr/>
<% end %>


<%= form_for(@user) do |f| %>
  <%= f.error_messages %>

  <% if mode == "new" || Azimux::AxUser.allow_username_edits %>
    <p>
      <b>Username</b><br />
      <%= f.text_field :username %>
    </p>
  <% end %>

  <p>
    <b>E-mail address</b><br />
    <%= f.text_field :email %>
  </p>

  <% if mode == "new" %>
    <p>
      <b>Password</b><br />
      <%= f.password_field :password1 %>
    </p>

    <p>
      <b>Verify password</b><br />
      <%= f.password_field :password2 %>
    </p>
  <% end %>

  <% Azimux::AxUser.additional_registration_models.each do |model| %>
    <% model = model.name.underscore %>
    <%= render :partial  => "#{model.pluralize}/fields_for",
      :locals => {:mode => mode} -%>
  <% end -%>

  <p>
    <%= f.submit mode == "new" ? "Register" : "Save Changes" %>
  </p>
<% end %>

app/views/users/create.html.erb
<!-- users.create -->
Thank you for signing up!<br><br>

You must now activate your account.  An email has been sent to you with instructions on how to activate your account.

app/views/users/edit.html.erb
<%= render :partial => "users/new_or_edit", :locals => {:mode => "edit"} -%>

app/views/users/edit_password.html.erb
<%= form_for @user, :url => update_password_user_url(@user) do |f| %>
  <%= f.error_messages %>
  <% if params[:code] %>
    <p>
      <%= hidden_field_tag :code, params[:code] %>
    <% else %>
      <b>Current Password</b>
      <%= password_field_tag :password -%>
    </p>
  <% end %>

  <p>
    Please enter your new password
  </p>
  <p>
    <b>New Password</b><br />
    <%= password_field_tag :password1 %>
  </p>

  <p>
    <b>Verify new password</b><br />
    <%= password_field_tag :password2 %>
  </p>

  <%= f.submit "Submit New Password" %>
<% end %>

app/views/users/edit_verification.html.erb
<%= form_for @user, :url => update_verification_user_url(@user) do |f| %>
  <%= f.error_messages %>
  <p>
    Please click to activate your account.
  </p>
  <%= hidden_field_tag :code, params[:code] %>

  <%= f.submit "Activate my account!" %>
<% end %>

app/views/users/new.html.erb
<%= render :partial => "users/new_or_edit", :locals => {:mode => "new"} -%>