config/routes.rb
Rails.application.routes.draw do
  resources :roles

  resources :users do
    member do
      get :edit_password
      put :update_password
      get :edit_verification
      put :update_verification
    end
  end

  resources :password_reset_requests

  match "signin", :to => "accounts#signin", :as => "login"
  match "signout", :to => "accounts#signout", :as => "logout"
  match "permission_denied", :to => "accounts#permission_denied"
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :children, :join_table => :role_parent_child,
    :class_name => 'Role', :foreign_key => "parent_id",
    :association_foreign_key => "child_id"
  
  has_and_belongs_to_many :users
  
  def in_role?(role, visited = Set.new)
    if visited.include?(name)
      raise "recursive role structure!  found #{name} twice!"
    end
      
    visited << self

    if role.is_a?(Role)
      role = role.name
    else
      role = role.to_s
    end
      
    return true if role == name
      
    children.each do |child|
      return true if child.in_role?(role, visited)
    end
      
    false
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  include Azimux::RequireLoginController

  require_login
  require_role "admin"

  # GET /roles
  # GET /roles.xml
  def index
    @roles = Role.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @roles }
    end
  end

  # GET /roles/1
  # GET /roles/1.xml
  def show
    @role = Role.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/new
  # GET /roles/new.xml
  def new
    @role = Role.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @role }
    end
  end

  # GET /roles/1/edit
  def edit
    @role = Role.find(params[:id])
  end

  # POST /roles
  # POST /roles.xml
  def create
    ActiveRecord::Base.transaction do
      @role, hash = fill_role(params[:role])

      respond_to do |format|
        if @role.save
          flash[:notice] = 'Role was successfully created.'
          format.html { redirect_to(@role) }
          format.xml  { render :xml => @role, :status => :created, :location => @role }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /roles/1
  # PUT /roles/1.xml
  def update
    ActiveRecord::Base.transaction do
      @role, hash = fill_role(Role.find(params[:id]), params[:role])

      respond_to do |format|
        if @role.update_attributes(hash) && @role.save
          flash[:notice] = 'Role was successfully updated.'
          format.html { redirect_to(@role) }
          format.xml  { head :ok }
        else
          format.html { render :action => "edit" }
          format.xml  { render :xml => @role.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.xml
  def destroy
    ActiveRecord::Base.transaction do
      @role = Role.find(params[:id])
      @role.destroy

      respond_to do |format|
        format.html { redirect_to(roles_url) }
        format.xml  { head :ok }
      end
    end
  end

  protected
  def fill_role(role, hash = nil)
    unless hash
      if role.is_a? Hash
        hash = role
        role = nil
      else
        raise "Expected Hash"
      end
    end

    hash = hash.dup
    children = hash.delete('children')
    raise "no children listed" if children.nil?
    children = children.split("\n").map(&:strip).select {|s|!s.blank?}
    children.map! {|p| Role.find_by_name(p)}
    raise "bad roles" if children.any? {|p|p.blank?}

    role ||= Role.new(hash)
    role.children = children

    return role, hash
  end
end

app/helpers/roles_helper.rb
module RolesHelper
  def print_role(role)
    ret = "<p>#{h role.name}</p>\n"
    if !(children = role.children).blank?
      ret << "<ul>\n"
      children.each do |child| 
        ret << "<li>\n#{print_role(child)}\n</li>\n"
      end 
      ret << "</ul>\n"
    end
    ret
  end 
end

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= error_messages_for :role %>

<%= form_for(@role) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Roles</b><br />
    <%= text_area_tag 'role[children]', @role.children.map(&:name).join("\n")  %>
  </p>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% for role in @roles %>
  <tr>
    <td><%=h role.name %></td>
     <td><%= link_to 'Show', role %></td>
    <td><%= link_to 'Edit', edit_role_path(role) %></td>
    <td><%= link_to 'Destroy', role, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= error_messages_for :role %>

<%= form_for(@role) do |f| %>
  <p>
    <b>Name</b><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <b>Roles</b><br />
    <%= text_area_tag 'role[children]', @role.children.map(&:name).join("\n")  %>
  </p>

  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<%= print_role(@role) -%>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>