config/routes.rb
Rails.application.routes.draw do
  resources :roles

  resources :users do
    member do
      get :edit_password
      put :update_password
      get :edit_verification
      put :update_verification
    end
  end

  resources :password_reset_requests

  match "signin", :to => "accounts#signin", :as => "login"
  match "signout", :to => "accounts#signout", :as => "logout"
  match "permission_denied", :to => "accounts#permission_denied"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def signin
    username = params[:username]
    password = params[:password]

    if !username.blank? || !password.blank?
      user = User.authenticate(username, password)

      unless user
        add_errors("Invalid username or password.")
      else
        #make sure the user has validated.
        if !user.verified?
          add_errors("You need to validate your account
              before you can sign in.  Please check your email for instructions.")
        else
          #user successfully signed in
          user.last_login = (Time.zone || Time).now
          user.save!

          redirect_to complete_signin(user)
        end
      end
    end
  end

  def signout
    session[:user] = nil
    dest = (respond_to? :home_url) ? home_url : '/'
    dest ||= "/"

    redirect_to(dest)
  end

  protected
  def complete_signin(user)
    session[:user] = user.id
    action = session[:intended_action]
    controller = session[:intended_controller]
    params_local = {}

    if session[:intended_params]
      session[:intended_params].each_pair do |key, val|
        if !params[key]
          if key == '_method'
            params_local['_method'] = val.to_sym
            params_local[:method] = val.to_sym
          else
            params_local[key] = val
          end
        end
      end
    end

    ["path", "params", "controller", "action"
    ].each {|key| session[("intended_" + key).to_sym] = nil}

    [:intended_action, :intended_params, :intended_controller].each do |key|
      session.delete(key)
    end

    if !action || !controller
      return root_url
    end

    params_local.merge({:action => action, :controller => controller})
  end

  def add_errors message
    require 'ostruct'

    @form        ||= OpenStruct.new
    @form.errors ||= ActiveModel::Errors.new(self)
    @form.errors.add(:base, message)
  end
end

app/views/accounts/_signin_form.html.erb
<% user = self.user || User.new
url_for_opts = {:protocol => "https"} if Azimux::AxUser.ssl_enabled?
url_for_opts ||= {}
%>
<% if session[:user] %>
  You are logged in as <%= user.username %>.<br/>
  <%= link_to "Logout", logout_url %>
<% else %>

  <%= form_tag login_url(url_for_opts) do %>
    <%= error_messages_for :form, 
      :message => nil, :header_message => nil %>

    <p>
      <b>Username:</b>
      <%= text_field_tag "username", params[:username] %>
    </p>

    <p>
      <b>Password:</b>
      <%= password_field_tag "password" %>
    </p>

    <%= submit_tag "Sign in" %>
  <% end %>

  Not registered?  <%= link_to "Register Here", new_user_url %><br/>
  Forgot your password?  <%= link_to "Click Here", new_password_reset_request_url %>
<% end %>

app/views/accounts/_signin_hor_form.html.erb
<% user = self.user || User.new
url_for_opts = {:protocol => "https", :only_path => false} if Azimux::AxUser.ssl_enabled?
url_for_opts ||= {}
-%>
<% if session[:user] -%>
  You are logged in as <%= user.username -%>
  <%= link_to "Logout", logout_url -%>
<% else -%>
  <%= form_tag login_url(url_for_opts) do -%>
    <b>Username:</b>
    <%= text_field_tag "username", params[:username], :size=>"5" -%>

    <b>Password:</b>
    <%= password_field_tag "password","", :size=>"5" -%>

    <%= submit_tag "Sign in" -%>
  <% end -%>
  <%= link_to "Register", new_user_url -%>
  <%= link_to "Forgot your password?", new_password_reset_request_url(url_for_opts) -%>
<% end %>

app/views/accounts/permission_denied.html.erb
<h1>Permission Denied</h1>

<p>Your account does not have permission to perform this action</p> 

app/views/accounts/signin.html.erb
<% options = { :action => "signin" } 
if @intended_method
  options.merge!({:method => @intended_method})
end %>

<%= vertical_signin_form %>